name: Check Websockets and Supabase Versions

on:
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install supabase
        pip install websockets

    - name: Check realtime dependencies
      run: |
        pip show realtime || echo "Realtime package not installed"
        pip show realtime | grep Requires || echo "No dependencies found"
    - name: Check full details of realtime package
      run: |
        pip show realtime
    - name: Run version check script
      run: python check_versions.py
