name: XRP Rich List Scraper

on:
  repository_dispatch:
    types: [cron-job]
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 115

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # スクレイピング用の依存関係インストール
    - name: Install scraper dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.27.1
        pip install xrpl-py==3.0.0

    # スクレイピング実行
    - name: Run scraper
      run: python scraper.py

    # スクレイピング用ライブラリをアンインストール
    - name: Uninstall scraper dependencies
      run: |
        pip uninstall -y selenium xrpl-py

    # アップローダー用の依存関係インストール
    - name: Install uploader dependencies
      run: |
        pip install supabase==2.7.1

    # アップロード実行
    - name: Run uploader
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python uploader.py

    # Cloudflareのデプロイフック
    - name: Trigger Cloudflare Build Hook
      if: success()
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CLOUDFLARE_DEPLOY_HOOK}"
      env:
        CLOUDFLARE_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}