name: XRP Rich List Scraper

on:
  repository_dispatch:
    types: [cron-job]
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 59

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # スクレイピング用の依存関係インストール
    - name: Install scraper dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.27.1
        pip install xrpl-py==3.0.0
        pip install aiohttp==3.11.8

    # スクレイピング実行
    - name: Run scraper
      run: | 
        python loader.py
        python validator.py

    # スクレイピング用ライブラリをアンインストール
    - name: Uninstall scraper dependencies
      run: |
        pip uninstall -y selenium xrpl-py aiohttp

    # アップローダー用の依存関係インストール
    - name: Install uploader dependencies
      run: |
        pip uninstall -y websockets supabase tweepy
        pip install supabase==2.7.1
        pip install realtime==2.3.0
        pip install websockets==10.4
        pip install tweepy==4.14.0

    # アップロード実行
    - name: Run uploader
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python uploader.py

    # Cloudflareのデプロイフック
    - name: Trigger Cloudflare Build Hook
      if: success()
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CLOUDFLARE_DEPLOY_HOOK}"
      env:
        CLOUDFLARE_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}

    # ポスト実行
    - name: Run post
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: python post-alert.py